config/routes.rb
NhsPatientlist::Application.routes.draw do
  devise_for :users

  resources :patient_lists do
    resources :handovers, :only => [:new, :create]
  end

  resources :memberships, :only => [:create, :destroy, :update]

  resources :to_do_items

  resources :patient_history, only: [:show]

  root :to => "patient_lists#index"
end

app/controllers/handovers_controller.rb
class HandoversController < ApplicationController
  expose(:patient_list) { PatientList.find params[:patient_list_id] }

  def new
    @patients_with_to_do_items = patient_list.to_do_items.where("state IN (?)", ["todo", "pending"]).group_by(&:patient)
    @patient_lists = PatientList.where("id != ?", patient_list.id)
  end

  def create
    if params[:handover][:to_do_items].present?
      to_do_items = patient_list.to_do_items.where("id IN (?)", params[:handover][:to_do_items])

      if to_do_items.any?
        new_list = PatientList.find params[:handover][:to_list]
        to_do_items.each do |item|
          item.handover_to(new_list)
        end
      end
      redirect_to patient_list_path(patient_list)
    else
      flash[:error] = "You must select at least one item to hand over"
      redirect_to new_patient_list_handover_path(patient_list)
    end
  end

end

app/helpers/handovers_helper.rb
module HandoversHelper
end

app/views/handovers/new.html.erb
<div class="page-header">
  <h1>
    Handover tasks
    <small><%= patient_list.name %></small>
  </h1>
</div>

<%= simple_form_for :handover, url: patient_list_handovers_path(patient_list) do |f| %>

  <fieldset>
    <% @patients_with_to_do_items.each do |patient, to_do_items| %>

      <legend><%= patient.name %></legend>

      <% to_do_items.each do |item| %>
        <label class="checkbox">
          <%= check_box_tag "handover[to_do_items][]", item.id, nil, id: item.description.parameterize %>
          <%= item.description %>
        </label>
      <% end %>

    <% end %>

  </fieldset>

  <%= f.input :to_list, collection: @patient_lists %>

  <div class="form-actions">
    <%= f.button :submit, "Hand over to do items", class: "btn-primary" %>
  </div>

<% end %>