config/routes.rb
NhsPatientlist::Application.routes.draw do
  devise_for :users

  resources :patient_lists do
    resources :handovers, :only => [:new, :create]
  end

  resources :memberships, :only => [:create, :destroy, :update]

  resources :to_do_items

  resources :patient_history, only: [:show]

  root :to => "patient_lists#index"
end

app/models/patient_detail.rb
class PatientDetail
  extend Forwardable

  def_delegators :@admission, :currward, :admconsultcode
  def_delegators :@patient, :hospno, :name, :birthdate, :sex, :pmh, :allergies, :firstnames, :lastname, :pastmedhx, :pat_id, :pendings, :to_dos, :risk_level, :risk_level=

  alias :ward :currward
  alias :pmh :pastmedhx
  alias :patient_id :pat_id

  attr_reader :patient, :admission

  def self.admitted
    Admission.admitted.map{|a| PatientDetail.new(a)}
  end
  def self.in_ward(ward)
    Admission.admitted.where(:currward=>ward).map{|a| PatientDetail.new(a)}
  end

  def initialize(admission)
    @admission = admission
    @patient = admission.patient

    if @patient.risk_level_events.empty?
      @patient.risk_level = "low"
    end
  end

  def name
    "#{firstnames} #{lastname}"
  end

  def consultant_name
    if @admission.consultant
      @admission.consultant.consultname
    else
      @admission.admconsultcode
    end
  end
end

app/views/patient_details/_details_table.html.erb
<table>
    <thead>
      <th>risk level</th>
      <th>ward</th>
      <th>consultant</th>
      <th>details</th>
      <th>pmh</th>
      <th>allergies</th>
      <th>pending</th>
      <th>todo</th>
      <th>actions</th>
    </thead>
  <tbody>
    <% patient_details.each do |patient| %>
      <tr class='patient_detail' data-patient-id="<%=patient.patient_id%>">
        <td class='risk-level'>
          <%= form_tag(update_risk_level_patient_path(patient.patient_id), :method => "post", :remote => true, :class => 'risk-level') do %>
            <span>
              <%= select_tag "risk_level", options_for_select(["low","medium","high"], :selected=>patient.risk_level) %>
              <%= submit_tag "Update Risk Level" %>
              <%= image_tag('spinner.gif', :class => 'ajax-wait') %>
            </span>
          <% end %>
          <div class="drag-handle">&oplus;</div>
        </td>
        <td><%= patient.ward %></td>
        <td><%= patient.consultant_name %></td>
        <td class="details">
          <p>Name: <%= patient.name %> (<%= patient.sex %>)</p>
          <p>Hospital num: <%= patient.hospno %></p>
          <p>DOB: <%= patient.birthdate %></p>
        </td>
        <td><%= patient.pmh %></td>
        <td><%= patient.allergies %></td>
        <td><%= link_to render('patient_detail_to_do',:to_dos=>patient.pendings), edit_patient_path(patient.patient_id, :ward=>nil) %></td>
        <td><%= link_to render('patient_detail_to_do',:to_dos=>patient.to_dos), edit_patient_path(patient.patient_id, :ward=>nil) %></td>
        <td>
          <p>
            <%= link_to "history", history_patient_path(patient.patient_id, :ward=>nil) %>
          </p>
          <% if controller_name == 'patient_lists' %>
            <p><%= link_to "remove from this list", url_for(:action => :destroy, :controller => :memberships,
                                                            :patient_id      => patient.patient_id,
                                                            :patient_list_id => own_patient_list.id),
                                                            :class           => 'remove', 
                                                            :method => :delete  %>
          <% else %>
            <p><%= link_to "add to list", patient_path(patient.patient_id) %></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>