config/routes.rb
NhsPatientlist::Application.routes.draw do
  devise_for :users

  resources :patient_lists do
    resources :handovers, :only => [:new, :create]
  end

  resources :memberships, :only => [:create, :destroy, :update]

  resources :to_do_items

  resources :patient_history, only: [:show]

  root :to => "patient_lists#index"
end

app/models/patient_list.rb
class PatientList < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :dependent => :destroy
  has_many :patients, :through => :memberships
  has_many :to_do_items

  has_many :handover_items, :foreign_key => "patient_list_from_id"
  has_many :handed_over_items, through: :handover_items, source: :to_do_item, uniq: true

  validates :name, :presence => true,
            :uniqueness => {:scope => :user_id, :message => "must be unique"}

  attr_accessible :name, :user

  default_scope order("name")

  def currently_handed_over_items(patient)
    handed_over_items.for_patient(patient) - to_do_items
  end

  def all_items_with_state(state, patient)
    state_to_do_items = to_do_items.send(state).for_patient(patient)
    state_handed_over_items = handed_over_items.for_patient(patient).where("to_do_items.state = ?", state)

    (state_to_do_items + state_handed_over_items).uniq
  end
end

app/controllers/patient_lists_controller.rb
class PatientListsController < ApplicationController
  expose(:patient_list) { PatientList.find params[:id] }

  # GET
  def index

  end

  # GET
  def show
  end

  # POST
  def create
    new_list = current_user.patient_lists.new params[:patient_list]
    if new_list.save
      redirect_to patient_list_path(new_list), :notice => "Created #{new_list.name}"
    else
      flash[:alert] = "Could not create list: #{new_list.errors.full_messages.join(",")}"
      redirect_to patient_lists_path
    end
  end
end

app/views/patient_lists/_patient_list.html.erb
<% membership = patient.memberships.where(:patient_list_id => patient_list.id).first %>

<div class="patient-detail risk-level-<%= membership.risk_level %>">
  <div class="patient-detail-header">
    <div class="patient-details">
      <h2><%= patient.name %></h2>

      <dl class="dl-horizontal muted">
        <dt>Hospital Number</dt>
        <dd><%= patient.hospno %></dd>
        <dt>Ward</dt>
        <dd><%= patient.current_ward %></dd>
      </dl>
    </div>

    <div class="patient-membership-actions">
      <%= form_for membership, :method => :delete do %>
        <%= link_to "View patient history", patient_history_path(patient), class: "btn btn-mini" %>
        <%= submit_tag "Remove from list", class: "btn btn-danger btn-mini" %>
      <% end %>
    </div>
  </div>

  <div class="patient-detail-risk-level">
    <%= simple_form_for membership, method: :put, remote: true, html: { class: "form-inline" } do |f| %>
      <% %w(high medium low).each do |risk_level| %>
        <label class="radio inline">
          <%= radio_button_tag "membership[risk_level]", risk_level, membership.risk_level == risk_level, id: "risk_level_#{membership.id}_#{risk_level}" %>
          <%= risk_level %>
        </label>
      <% end %>
    <% end %>
  </div>

  <div class="patient-detail-tasks row">
    <div class="span3">
        <div class="well">
          <h4>Create new item</h4>

          <%= simple_form_for ToDoItem.new do |f| %>
            <%= f.hidden_field :patient_id, :value => patient.id %>
            <%= f.hidden_field :patient_list_id, :value => patient_list.id %>

            <%= f.input :description, input_html: { class: "input-block-level" } %>
            <%= f.input :grade_id, collection: Grade.all, label: "Minimum grade", input_html: { class: "input-block-level" } %>

            <%= f.button :submit, "Add item", class: "btn-primary btn-small" %>
          <% end %>
        </div>
    </div>

    <div class="span6 pull-right">
      <div class="patient-tasks">
        <%= render partial: "patient_tasks",
                   collection: %w(todo pending done),
                   as: :state,
                   locals: { patient: patient, patient_list: patient_list }  %>
      </div>

      <% other_to_do_items = patient.to_do_items.joins(:patient_list).where("patient_list_id != ?", patient_list.id) %>
      <% if other_to_do_items.count > 0 %>
        <div class="patient-other-tasks">
          <div class="accordion" id="accordion-<%= membership.id %>">
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-<%= membership.id %>" href="#accordion-<%= membership.id %>-tasks">
                  <%= pluralize(other_to_do_items.count, "item") %> in other patient lists
                </a>
              </div>
              <div class="accordion-body collapse" id="accordion-<%= membership.id %>-tasks">
                <div class="accordion-inner">
                  <% other_to_do_items.group_by{ |item| item.patient_list.name }.each do |list, items| %>
                    <p><%= link_to list, patient_list_path(items.first.patient_list) %></p>

                    <ul>
                      <% items.each do |item| %>
                        <li><%= item.description %>: <%= item.state %></li>
                      <% end %>
                    </ul>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>

</div>

app/views/patient_lists/_patient_tasks.erb
<div class="nav-header"><%= state %></div>

<% patient_list.all_items_with_state(state, patient).each do |item| %>
<div class="patient-task">
  <div class="pull-left">
    <span class="<%= state %>"><%= item.description %></span>
    <% if item.grade %>
      <br />
      <span class="muted">Min. grade: <%= item.grade.title %></span>
    <% end %>
  </div>

  <div class="patient-task-actions span3 pull-right">
    <% if item.patient_list == patient_list %>
      <%= simple_form_for item do |f| %>
        <%= f.input :state, collection: %w(todo pending done), label: false, include_blank: false, input_html: { onchange: 'this.form.submit()' } %>
      <% end %>
      <%= link_to 'Delete item', to_do_item_path(item), class: 'btn btn-mini btn-danger', method: :delete, confirm: 'Are you sure you want to delete this to do item?' %>
    <% else %>
      <span class="muted">Handed over to <%= link_to item.patient_list.name, patient_list_path(item.patient_list) %></span>
    <% end %>
  </div>
</div>
<% end %>

app/views/patient_lists/index.html.erb
<div class="page-header">
  <h1>Patient lists</h1>
</div>

<%= simple_form_for PatientList.new, :url => patient_lists_path, :html => { :class => "form-inline" } do |f| %>
  <%= f.input :name, label: false, :wrapper => :append do %>
    <%= f.input_field :name, label: false, placeholder: "Add new patient list" %>
    <%= button_tag content_tag(:i, nil, class: "icon-white icon-plus"), type: "submit", class: "btn btn-primary" %>
  <% end %>
<% end %>

<ul class="nav nav-tabs nav-stacked">
  <% PatientList.all.each do |list| %>
    <li><%= link_to list.name, patient_list_path(list) %></li>
  <% end %>
</ul>

app/views/patient_lists/show.html.erb
<div class="row">
  <div class="span3">
    <div class="nav nav-table">
      <% Patient.not_discharged.uniq.each do |patient| %>
        <div class="nav-table-cell clearfix">
          <%= form_tag memberships_path, class: "add-patient-form" do %>
            <%= hidden_field_tag "patient_id", patient.id %>
            <%= hidden_field_tag "membership[patient_list]", patient_list.id %>

              <p>
                <strong><%= patient.lastname %></strong> <%= patient.firstnames %><br />
                <span class="muted"><%= patient.hospno %></span>
              </p>

              <%= button_tag "Add to list", type: "submit", class: "btn btn-primary btn-mini" %>
              <%= link_to "View patient history", patient_history_path(patient), class: "btn btn-mini", title: "View patient history" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="span9">
    <div class="page-header">
      <h1><%= patient_list.name %></h1>
    </div>

    <%= render :partial => "patient_list",
          :collection => patient_list.patients,
          :as => :patient,
          :locals => {:patient_list => patient_list}
    %>

    <hr />

    <p><%= link_to "Hand over to do items", new_patient_list_handover_path(patient_list), class: "btn btn-primary" %></p>
  </div>
</div>