config/routes.rb
NhsPatientlist::Application.routes.draw do
  devise_for :users

  resources :patient_lists do
    resources :handovers, :only => [:new, :create]
  end

  resources :memberships, :only => [:create, :destroy, :update]

  resources :to_do_items

  resources :patient_history, only: [:show]

  root :to => "patient_lists#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "NHS Patient List" %></title>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "NHS Patient List", root_path, class: "brand" %>

          <% if user_signed_in? %> 
            <ul class="nav">
              <li><%= link_to "Patient Lists", patient_lists_path %></li>
            </ul>

            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.email %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <div id="content" class="container">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div> 
  </body>
</html>